# Generated by Django 5.0 on 2024-01-01 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=50, null=True)),
                ('dob', models.DateField(blank=True, default='', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
