# Generated by Django 4.2.7 on 2024-01-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesettings', '0005_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='Unknow User', max_length=50, null=True),
        ),
    ]
