# Generated by Django 4.2.7 on 2024-01-08 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profilesettings', '0007_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
