# Generated by Django 4.2.7 on 2024-01-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilesettings', '0010_rename_user_profile_username_alter_profile_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
