# Generated by Django 5.0 on 2024-01-01 13:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profilesettings', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('caption', models.TextField()),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='posted_pictures', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilesettings.profile')),
                ('profile_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_pfp', to='profilesettings.profile')),
            ],
        ),
    ]
