# Generated by Django 5.0 on 2024-01-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comments'),
        ('profilesettings', '0012_alter_profile_dob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
